// ============================================================
// IMPORTANT: This file is auto-generated by Firebase.
// DO NOT write this file manually.
//
// HOW TO GENERATE THIS FILE:
// 1. Install FlutterFire CLI:
//    → run in terminal: dart pub global activate flutterfire_cli
//
// 2. Login to Firebase:
//    → run: firebase login
//
// 3. Configure your project:
//    → run: flutterfire configure
//    → Select your "nexora" Firebase project
//    → Select Android (and iOS if needed)
//
// This will auto-generate firebase_options.dart in your lib/ folder.
// Replace this placeholder file with that generated file.
// ============================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // This will be replaced by flutterfire configure output
    throw UnsupportedError(
      'Please run: flutterfire configure\n'
          'to generate your firebase_options.dart file.',
    );
  }
}