// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCezVgCJ9m_Poph0p_8z4SaEjPYwlfXHtc',
    appId: '1:669826745634:web:f47ce374ef388cd7e8117b',
    messagingSenderId: '669826745634',
    projectId: 'nexora2026-561c6',
    authDomain: 'nexora2026-561c6.firebaseapp.com',
    storageBucket: 'nexora2026-561c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClxUq-LFTe0CGPLgHXZ9ZqqNCEwYz3W0s',
    appId: '1:669826745634:ios:0ce165c936834c8ee8117b',
    messagingSenderId: '669826745634',
    projectId: 'nexora2026-561c6',
    storageBucket: 'nexora2026-561c6.firebasestorage.app',
    iosBundleId: 'com.example.nexora',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClxUq-LFTe0CGPLgHXZ9ZqqNCEwYz3W0s',
    appId: '1:669826745634:ios:0ce165c936834c8ee8117b',
    messagingSenderId: '669826745634',
    projectId: 'nexora2026-561c6',
    storageBucket: 'nexora2026-561c6.firebasestorage.app',
    iosBundleId: 'com.example.nexora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCezVgCJ9m_Poph0p_8z4SaEjPYwlfXHtc',
    appId: '1:669826745634:web:4f79a18fc93ab87ce8117b',
    messagingSenderId: '669826745634',
    projectId: 'nexora2026-561c6',
    authDomain: 'nexora2026-561c6.firebaseapp.com',
    storageBucket: 'nexora2026-561c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOodG8ZUcLgeRf_9LXAkVf2v0oM3tqHiY',
    appId: '1:669826745634:android:551dce384626c3fee8117b',
    messagingSenderId: '669826745634',
    projectId: 'nexora2026-561c6',
    storageBucket: 'nexora2026-561c6.firebasestorage.app',
  );
}
